import React from 'react';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor: "#4369B0",
    },
    facebook:{
        position: 'absolute',
        marginTop: 170,
    },
    img:{    
        marginLeft: 30,
        width: 50,
        height: 50,
        position: 'absolute',
    },
    face:{
        color: "#FFFFFF",
        marginLeft: 98,
        fontFamily: 'Roboto',
        fontStyle: 'normal',
        fontWeight: "900",
        fontSize: 42.11,
        lineHeight: 49,
        position: 'absolute',
        width: 218.42,
        height: 50,
        marginRight: 97.58,
        letterSpacing: 0.03,
    },
    textInput:{
        color:"#FFFFFF",
        width: 320,
        height: 42,
        marginLeft: 18,
        backgroundColor: "#FFFFFF",
        marginTop: 300,
        marginRight: 18,
        position: 'absolute',
    },
    textInputt:{
        color:"#FFFFFF",
        width: 320,
        height: 42,
        marginLeft: 18,
        backgroundColor: "#FFFFFF",
        marginRight: 18,
        position: 'absolute',
        marginTop: 370,
    },
    meubotao:{
        backgroundColor:"#213873",
        width: 320,
        height: 42,
        marginLeft: 18,
        textAlign: 'center',
        marginTop: 440,
        fontFamily: 'Roboto',
        fontStyle: 'normal',
        fontWeight: "bold",
        fontSize: 25,
        borderRadius:10,
    },
    meubotaoTexto:{
        color:"#F5FFFF",
        textAlign: 'center',
        fontFamily: 'Roboto',
        fontStyle: 'normal',
        fontWeight: "bold",
        fontSize: 25,
    },
    upfor:{
        marginTop: 670,
        color: "#FFFFFF",
        marginLeft: 105,
        width: 163,
        height: 19,
        fontFamily: 'Roboto',
        fontStyle: 'normal',
        fontWeight: "normal",
        position: 'absolute',
        fontSize: 16,
    },
});